site_name: Doce GSR
site_author: Rafael Monteiro
site_url: https://rafaelmonteirorodriguessilva.github.io/doce-gsr/

repo_url: https://github.com/rafaelmonteirorodriguessilva/doce-gsr
edit_uri: edit/main/docs/

theme:
  name: material
  language: pt